services:
  fluxer-rpc:
    image: ghcr.io/letruxux/fluxer-rpc:latest
    restart: unless-stopped
    environment:
      # required
      - TOKEN=
      - DISCORD_ID=

      # last.fm (only used when offline on discord) *
      - CHECK_LASTFM_WHEN_ONLINE=false
      - LASTFM_USER=
      - LASTFM_KEY=
      - LASTFM_UPDATE_INTERVAL_SECONDS=30

      # default status
      - ENABLE_DEFAULT_STATUS=true
      - DEFAULT_STATUS_TEXT="hiii"
      - DEFAULT_STATUS_EMOJI="🐬"

      # music
      - MUSIC_TEXT="{{artist}} - {{song}}"
      - MUSIC_EMOJI="🎧"
      - SHOW_MUSIC_TIME=false

      # coding
      - CODING_TEXT="Coding!"
      - CODING_EMOJI="💻"
      - CODING_APPS="visual studio code, intellij idea, intellij idea community, vscodium"

      # playing
      - PLAYING_TEXT="{{action}} {{name}}"
      - PLAYING_EMOJI="🎮"

      # priorities (lower is more important)
      - MUSIC_PRIORITY=0
      - CODING_PRIORITY=2
      - PLAYING_PRIORITY=1

      # multiple activities
      - SHOW_MULTIPLE_ACTIVITIES=true
      - MULTIPLE_ACTIVITIES_STYLE="plusCount"
      #  plusEmoji - 🎮 Playing GAME (15:00) (+🎧)
      #  emoji - 🎮 Playing GAME (15:00) (🎧)
      #  plusCount - 🎮 Playing GAME (15:00) (+1)


      # statuses (allowed: online, idle, dnd, invisible)
      - MIRROR_STATUS_FROM_DISCORD=false
      - ONLINE_STATUS="online"
      - ACTIVITY_STATUS="online"
      - MUSIC_STATUS="online"
      - OFFLINE_MUSIC_STATUS="idle"
      - OFFLINE_ACTIVITY_STATUS="invisible"

      # settings
      - SHOW_ACTIVITY_TIME=true
      - TIMER_UPDATE_INTERVAL_SECONDS=30
      - ROUND_TO_SECONDS=5

      # other
      - WATCHING_EMOJI="📺"
